name: Prettier
on: [pull_request]
jobs:
  Prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{jsx}
          same_commit: true
          only_changed: true